import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='flex gap-3 items-center h-14 bg-white text-black'>
          <img className='h-[26px]' src='/Reel-Talk-Logo.png'/>
          <div className='font-AvenirBlack'>REEL TALK</div>
          <div>Browse</div>
          <div>Community</div>
          <div>Discussions</div>
          <div>Search</div>
          <div>Watchlist</div>
          <div>Acc</div>
        </nav>
        {children}
      </body>
    </html>
  )
}
