export const genreData = [
    "✨ Action",
    "🎢 Adventure",
    "🔞 Adult",
    "🖍 Animation",
    "📖 Biography",
    "🛕 Bollywood",
    "😂 Comedy",
    "🕵️‍♀️ Crime",
    "🌪 Disaster",
    "🎥 Documentary",
    "✨ Drama",
    "🎢 Family",
    "⚔ Fantasy",
    "🖍 Film-Noir",
    "📖 History",
    "🎃 Horror",
    "🎮 Game-Show",
    "🕵️‍♀️ Independent",
    "🌪 International",
    "🎼 Music",
  ];